version: '3'
services:

  backend:
    image: stock/backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      - pq_prod_network

  postgres_db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stock_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pq_prod_network

networks:
  pq_prod_network:
    ipam:
      driver: default